### ISSUE TITLE
How to inference

### ISSUE THREAD

**Issue by WuNein** [neuralmagic/AutoFP8#1]
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/root/run_model.py", line 20, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3155, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 149, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 73, in from_dict
    raise ValueError(
ValueError: Unknown quantization type, got fp8 - supported types are: ['awq', 'bitsandbytes_4bit', 'bitsandbytes_8bit', 'gptq', 'aqlm', 'quanto']
```
Quantization is fine, i success run the script, but i don't know how to inference in a standalone script
```
time cost calulate in the quantization script

12.44 BF16
30.11 FP8 Dyn
21.47 FP8 Static

GPU memory is lower in FP8 mode
```
i don't know how to inference in a standalone script
```
import argparse
import gc
import re
from typing import Tuple

import torch
import torch.functional as F
import transformers
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer


tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/fp8")
sample_input_tokens = tokenizer.apply_chat_template(
    [{"role": "user", "content": "Write a quick sort python code"}],
    add_generation_prompt=True,
    return_tensors="pt",
).to("cuda")

model = AutoModelForCausalLM.from_pretrained(
        "/root/autodl-tmp/fp8", torch_dtype="auto", device_map="auto"
)
print(model)
start_time = time.time()
for i in range(10):
    output = model.generate(input_ids=sample_input_tokens, max_new_tokens=50)
print(tokenizer.decode(output[0]))
end_time = time.time()
print(end_time - start_time)
```

**Comment by mgoin** [comment]
@WuNein thanks for the interest but this format is not supported with Transformers yet! The first working inference example will be implemented in vLLM with this PR https://github.com/vllm-project/vllm/pull/4332

**Comment by WuNein** [comment]
@mgoin FP8 , whatever training for inference is a long way.
https://huggingface.co/docs/accelerate/v0.29.3/concept_guides/low_precision_training
MS-AMP, TE engine , I doubt none of them work quite smooth~

**Comment by WuNein** [comment]
@mgoin I see the commit merged? So it is usable?
